load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "event_future_lib",
    hdrs = ["event_future.h"],
    srcs = ["event_future.cc"],
    deps = [
        "@libevent//:libevent",
    ]
)